*- Selecciono Docuemnto
SELECT M.* ;
FROM ArtMovCab M ;
WHERE M.NroSec == 0 ;
INTO CURSOR Tmp
SCATTER NAME oCab BLANK
USE IN Tmp

*- Datos Iniciales
oCab.NroSec = 0
oCab.CodAlm = ""
oCab.TipMov = "S"
oCab.TipTsc = "01"
oCab.Periodo = SUBS(DTOS(DATE()),1,6)
oCab.FecDoc = DATE()
oCab.TipDoc = "GS"
oCab.IndSit = 1 && PENDIENTE
oCab.FecSit = DATE()
lnTipReg = 2
lcTipOpc = "A"
lnRetorno = 0
DO FORM &gRuta\forms\frmMov_AlmSal WITH lnTipReg,lcTipOpc,oCab && TO lnRetorno
lnNroSec = oCab.NroSec
RELEASE oCab
RETURN

*NROSEC,CODALM,PERIODO,FECDOC,TIPMOV,TIPTSC
*TIPDOC,NRODOC,SERDOC,SECDOC
*TIPAUX,CODAUX,NOMAUX,NRORUC,DIRECCION,CODPAIS,CODCDD,CODPOSTAL
*NROORDCOM,TIPDOCREF,NRODOCREF,NROSECREF,NROFAC,NROGUI
*TIPAUXVDD,CODAUXVDD,INDCOSPRM,INDPRE,INDCOS,TIPPRE
*CODMND,TIPMND,TIPCAM,IMPCAM,PCJIGV,INDIGV,INDSIT,FECSIT
*CANTOT,IMPTOT,NROSECDET,NROITM,
*USUADD,FECADD,USUACT,FECACT,SIMBOL,TIPORD,NROORD,SECORD,INDREG,TIPREG